# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

covNonSep <- function(DS, DT, c, thetas, thetat) {
    .Call('_STplm_covNonSep', PACKAGE = 'STplm', DS, DT, c, thetas, thetat)
}

covNonSep2 <- function(DS, DT, c, thetat, thetas) {
    .Call('_STplm_covNonSep2', PACKAGE = 'STplm', DS, DT, c, thetat, thetas)
}

covNonSep3 <- function(DS, DT, c, thetat, thetas, theta3) {
    .Call('_STplm_covNonSep3', PACKAGE = 'STplm', DS, DT, c, thetat, thetas, theta3)
}

covSep <- function(DS, DT, c, thetas, thetat) {
    .Call('_STplm_covSep', PACKAGE = 'STplm', DS, DT, c, thetas, thetat)
}

loglikeCpp <- function(theta0, CovStructure, loctim, DS, DT, Z, truncate, lambda, pterm, DDnew) {
    .Call('_STplm_loglikeCpp', PACKAGE = 'STplm', theta0, CovStructure, loctim, DS, DT, Z, truncate, lambda, pterm, DDnew)
}

logProfileCpp <- function(theta0, CovStructure, loctim, DS, DT, Xprime, Zprime, truncate, lambda, pterm, DDnew) {
    .Call('_STplm_logProfileCpp', PACKAGE = 'STplm', theta0, CovStructure, loctim, DS, DT, Xprime, Zprime, truncate, lambda, pterm, DDnew)
}

nonparlogprof <- function(theta0, CovStructure, loctim, DS, DT, Zprime, truncate, lambda, pterm, DDnew) {
    .Call('_STplm_nonparlogprof', PACKAGE = 'STplm', theta0, CovStructure, loctim, DS, DT, Zprime, truncate, lambda, pterm, DDnew)
}

